# Generated by Django 6.0.2 on 2026-03-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='quantity_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='quantity_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='time_takes',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='unity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
