# Generated by Django 6.0.2 on 2026-03-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateField(blank=True, null=True)),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('frequence', models.IntegerField(blank=True, null=True)),
                ('instructionRepas', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
