# Generated by Django 6.0.2 on 2026-03-10 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0002_medicament_date_end_medicament_date_start_and_more'),
        ('traitement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='medecament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicament.medicament'),
        ),
    ]
