# Generated by Django 6.0.2 on 2026-04-28 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_password'),
        ('traitement', '0002_traitement_medecament'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='paitent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
