"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv 
import os
load_dotenv( ".env" ) 


# Google OAuth
GOOGLE_OAUTH_CLIENT_ID = os.getenv( "GOOGLE_OAUTH_CLIENT_ID" ) 
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv( "GOOGLE_OAUTH_CLIENT_SECRET" ) 
GOOGLE_OAUTH_CALLBACK_URL = os.getenv( "GOOGLE_OAUTH_CALLBACK_URL" )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(xnig)_(nvcn_fxo%5g2xo6^0nj$km7*0!e#y_g#&%x#tpm7yb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
       'allauth' , 
    'allauth.account' , 
    'allauth.socialaccount' , 
    'dj_rest_auth.registration',
    'corsheaders',
    'user1',
    'patient',
    'medicament',
    'traitement',
    'allauth.socialaccount.providers.google',
    'rest_framework.authtoken',
    'rappel',
]
SITE_ID = 1

AUTH_USER_MODEL = 'user1.User'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
     "allauth.account.middleware.AccountMiddleware" ,
      'corsheaders.middleware.CorsMiddleware',
]
ACCOUNT_AUTHENTICATION_METHOD = "email"  
ACCOUNT_USERNAME_REQUIRED = False 
ACCOUNT_EMAIL_REQUIRED = True 
ACCOUNT_EMAIL_VERIFICATION = "none"
REST_FRAMEWORK = {
    
    'DEFAULT_AUTHENTICATION_CLASSES': (
        
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
    
}
CORS_ALLOWED_ORIGINS = [
    'http://localhost:4200',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'project1',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
#  SOCIALACCOUNT_EMAIL_AUTHENTICATION = True 
# # Connexion du compte local et du compte social si un compte local avec cette adresse e-mail existe déjà
#  SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True 
# SOCIALACCOUNT_PROVIDERS = { 
#     " google" : { 
#         "APPS" : [ 
#             { 
#                 "client_id" : GOOGLE_OAUTH_CLIENT_ID, 
#                 "secret" : GOOGLE_OAUTH_CLIENT_SECRET, 
#                 "key" : "" , 
#             }, 
#         ], 
#         "SCOPE" : [ "profile" , "email" ], 
#         "AUTH_PARAMS" : { 
#             "access_type" : "online" , 
#         }, 
#     } 
# }
