# Generated by Django 6.0.2 on 2026-04-28 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rappel', '0001_initial'),
        ('traitement', '0002_traitement_medecament'),
    ]

    operations = [
        migrations.AddField(
            model_name='rappel',
            name='isSnoozed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rappel',
            name='traitement',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='traitement.traitement'),
            preserve_default=False,
        ),
    ]
